### ISSUE TITLE
More of a question of understanding

### ISSUE THREAD

**Issue by riemers** [projectatomic/docker-novolume-plugin#9]
I looked at the plugin i thought i could deny certain items, but it doesn't deny 

```
docker run -v /:/test fedora sh  # works
```

Which is what i would want too, with future then allowing certain group/users only to use a volume with those rights.

Perhaps i am searching for the holy grail but my intentions would be to disallow the volumes because i don't want people to mount /etc and change the shadow file inside a container. I can give sudo rights to certain commands for docker, allowing them still freedom but those mounts make it pretty darn hard. Doing a regex on something:something:z|Z with sudo seems to me to not be the correct way. Would people still not be able to use these 'loopholes' even when using a plugin like this?

**Comment by rhatdan** [comment]
docker-novolume-plugin is only about blocking the use of internal volumes in a container, its main goal is to stop Dockerfile from using 

volume /var/foobar

There is nothing that can control a user that can get direct access to the docker.socket.  We have submitted patches to implement Authentication, so that we could be authorization plugins, but thusfar they have not been merged.

The best you can do is use sudo and control the docker lines the users are able to execute.
